server:
  port: 8004 #服务端口
#spring相关配置
url: /msg
spring:
  redis:
    port: 6379
    database: 1
    host: 120.78.179.106
    password: 110120119
  application:
    name: school-consumer-chat  #服务名
    redis:
      redisson:
        file: classpath:redisson.yml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver  #数据库驱动包
    url: jdbc:mysql://120.78.179.106:3306/chattest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机配置
      defaultZone: http://localhost:8000/eureka